FROM golang:1.24.2-alpine AS builder

RUN apk add --no-cache git gcc musl-dev

WORKDIR /app

COPY go.mod go.sum ./
RUN go mod download

COPY . .
RUN CGO_ENABLED=0 GOOS=linux go build -ldflags="-w -s" -o /server ./cmd/main.go

FROM alpine:latest

RUN apk add --no-cache docker-cli

WORKDIR /app

COPY --from=builder /server /server

EXPOSE 701

CMD ["/server"]
